### PR TITLE
Add NAS-Filter-Rule and User-Password RADIUS Attributes

### PR DESCRIPTION
**Pull request by MichaelWasher**
Add NAS-Filter-Rule and User-Password RADIUS Attributes

### CODE REVIEW

**Comment by MichaelWasher** [comment]
Someone should look at the User-Password and weigh in on where to place the encryption / decrypt functions. They appear to be working as expected just don't really know where to put them...

**Comment by Bairdo** [comment]
Out of curiosity what is User-Password used for?

There seems like a reasonable place, it's specific to that attribute.

**Comment by MichaelWasher** [comment]
It's there for sending non-eap based requests to RADIUS. Which is the core of my MAB functionality

**Comment by MichaelWasher** [comment]
Replaced by https://github.com/faucetsdn/chewie/pull/125

**Pull request closed without merging**
