### PR TITLE
state machine is tied to a PORT and src_mac. should cover case where …

### LINKED ISSUE #35: Could verify that all EAP packets in a sequence come from the same port.
If we have 2 hosts with same MAC (e.g. 1 good, 1 Malicious) and they try to authenticate, it could be possible to authenticate on the malicious port when good is successful if malicious sends eap packet before the radius access-accept has been received, and thus setting the sm.port_id_mac.

Basically we want to stop this. 2 obvious ways.
1. Make a state machine tied to a mac and port. So in the above case there would be 2 state machines.
2. some sort of verification logic.

Option 1 looks easier to implement.
Will also handle if 2 good, both would auth.

### PR DESCRIPTION
**Pull request by Bairdo**
…two identical macs are on the network

Closes #35

### CODE REVIEW

**Comment by Bairdo** [comment]
there's an error dont merge yet

**Comment by Bairdo** [comment]
#41 fixes the error. this can now be merged

**Comment by KitL** [comment]
I'm not particularly familiar with Chewie, but from the description it looks as though it would have been good to include a test. Is that possible?

**Comment by Bairdo** [comment]
Yea, it should. chewie.py is currently not tested here (in this repo) at all, i will look into it shortly.

**Comment by anarkiwi** [comment]
There's quite a few changes here which can't be merged for one reason or another. Please would you take a look at the build status to diagnose so we can move forward?

**Comment by Bairdo** [comment]
python3.4 failed on a state machine unit test https://travis-ci.com/faucetsdn/chewie/jobs/147919589 but passed on mine, and both passed when ran again, which sounds like a right pain.

Should i look into it?

**Comment by Bairdo** [comment]
interesting python3.5 failed on the same test case but different branch https://travis-ci.org/Bairdo/chewie/jobs/433203221

**Comment by Bairdo** [comment]
hopefully #48 fixes that issue.

**Pull request merged**
