### PR TITLE
Use pytransitions for eap state machine

### PR DESCRIPTION
**Pull request by Bairdo**
#65 

No features added.

### CODE REVIEW

**Comment by gizmoguy** [comment]
Failing due to pytype:

File "/home/travis/build/faucetsdn/chewie/chewie/eap_state_machine.py", line 679, in handle_message_received: No attribute 'process' on FullEAPStateMachine [attribute-error]

**Comment by Bairdo** [comment]
I've ignored the error, the method is created by the transitions library.

**Comment by gizmoguy** [comment]
Seems very unhappy on python3.5 for some reason, if you can fix before 10am I will put this PR in chewie 0.0.11, otherwise it will have to be part of the next release.

**Comment by gizmoguy** [comment]
#96 is now in please rebase and hopefully that will unstick travis which isn't running your latest commit for some unknown reason

**Comment by Bairdo** [comment]
Ive noticed faucetsdn's travis only runs a certain number of jobs at a time across all its repositories. So it could be waiting for another build to finish. and it looks like the faucet repo is running.

**Comment by Bairdo** [comment]
all pass here https://travis-ci.org/Bairdo/chewie/builds/466227356

**Comment by gizmoguy** [comment]
I ordered the travis jobs so that this would run. Looks good, I will release new chewie now.

**Pull request merged**
