### PR TITLE
Chewie can authenticate user via RADIUS Server with MD5 or TTLS

### PR DESCRIPTION
**Pull request by Bairdo**
- Supplicant can use MD5 or TTLS to authenticate, Chewie passes this through to a RADIUS Server.
- Should be multi user (untested).
- Also de-lint line spacing, unused imports.

### CODE REVIEW

**Comment by Bairdo** [comment]
Still TODO
- Unittests
  - Success2/Failure2 states
  - retransmit(2)
  - Discard(2)
  - Drop corrupt packets (during parsing)
- Re transmit if packet lost
- Discard/Integrity check packets in statemachine, parsing does handle this to a degree.
- Tidy up the contract of what object goes in/out of the statemachine.
- Possibly some unnecessary parsing, packing, parsing going on.
- Logging - use correct levels, log useful things not just everything for debugging.

**Comment by Bairdo** [comment]
Sorry big commit, not sure how I could break up the state machine part into smaller commits.
I'll be away from 7/7/18 - 15/7/18 so wont be able to reply

**Comment by gizmoguy** [comment]
Hi @Bairdo,

Myself and @anarkiwi have taken over maintaining this project. Just attempting to get up to speed here, looks like you have a few more items on the list to check off before this PR is complete? You will let us know when you want the PR reviewed?

Brad

**Comment by Bairdo** [comment]
Hi @gizmoguy,
Yes a couple more things, hopefully should be done by end of tomorrow. I'll ping you here when they're up here.

**Comment by Bairdo** [comment]
Hi @gizmoguy 
I've missed calculating a hash, probably won't be ready by end of today.

Also that list is complete, except for logging - which i'm not sure how verbose it should be so i'll leave it as is for the moment.

**Comment by gizmoguy** [comment]
@Bairdo no worries, been quite busy today anyway so I wouldn't have got around to this. Hopefully I can get some time to work on this next week.

Assuming there are some tests we can run to validate the changes (it seems like there are a few) should be able to merge this in quite quickly.

**Comment by gizmoguy** [comment]
Thanks!

**Pull request merged**
