### PR TITLE
Periodic Reauthentication

### PR DESCRIPTION
**Pull request by Bairdo**
builds on top of #116.

### CODE REVIEW

**Comment by Bairdo** [comment]
test_chewie.py:test_port_status_changes() blocks forever.

**Comment by Bairdo** [comment]
Skipping broken test, test_chewie.py:test_port_status_changes()

Not particularly sure how to fix it atm. Will have another look tomorrow morning if at work (coming down with man flu).

The case should be tested over on the faucet integration tests, so could potentially be merged, (i don't mind either way).

**Comment by gizmoguy** [comment]
Hi @Bairdo, just letting you know we are deferring the faucet 1.9 release until tomorrow now.

On the off chance you are feeling better you have an extra day to get all this wrapped up. Otherwise we can include it in next weeks release.

**Comment by Bairdo** [comment]
So this PR was branched off of PR #116, but contains a bug or two which have been fixed in this PR. So either they can both be merged in or #116 can be deleted as it is contained in this one, without the errors.

**Pull request merged**
