### PR TITLE
Bug

### PR DESCRIPTION
**Pull request by Bairdo**
goes on top of #39 
Main issue was if a successful authed port (SM=disabled) was set to down, chewie would still send a success to faucet.

### CODE REVIEW

**Comment by Bairdo** [comment]
May also fix the bug 'this should never happen", if it's still occuring.

**Comment by KitL** [comment]
Could this include a test?

**Comment by Bairdo** [comment]
I'll take another look, but I wasn't sure how to reproduce the bug ('this should never happen') - (and it only happened intermittently). Just noticed it again while reading the RFC.

Will add a test for the first issue though

**Comment by Bairdo** [comment]
Ok, added a check in the tearDown to see if that error appears

**Comment by anarkiwi** [comment]
Thanks for adding the test. It will be brittle because if that assert text string changes then the assert will silently fail to catch the problem. Please correct that in a future test (e.g. via a conventional exception).

**Pull request merged**
