### PR TITLE
Push Docs to ReadTheDocs

### PR DESCRIPTION
**Pull request by MichaelWasher**
Add Configuration Files for ReadTheDocs
Add ReadMe to Docs 
Docs include Sphinx-built documentation

### CODE REVIEW

**Comment by MichaelWasher** [comment]
Link: https://michael-chewie.readthedocs.io/en/latest/

I left chewie.readthedocs.io available for use with the FaucetSDN account. 

@gizmoguy

**Comment by gizmoguy** [comment]
closes #130

**Comment by gizmoguy** [comment]
https://chewie.readthedocs.io/en/latest/

**Comment by gizmoguy** [comment]
fixes #130

**Pull request merged**
